database:
  host: "localhost"
  port: "27017"
  username: "admin"
  password: "admin"
  database: "magazin"
  max_connections: 20
  min_pool_size: 10
  auth: false
  replica_set: myReplicaSet

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

server:
  port: ":9999"
